export default [
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Gray',
    'hex': '#B7BAC3',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Gray/image_1.jpeg',
    'description': 'gray'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Gray',
    'hex': '#B7BAC3',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Gray/image_2.jpeg',
    'description': 'Back view (Gray)'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Gray',
    'hex': '#B7BAC3',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Gray/image_3.jpeg',
    'description': 'Bottle cap (Gray)'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Gray',
    'hex': '#B7BAC3',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Gray/image_4.jpeg',
    'description': ''
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Gray',
    'hex': '#B7BAC3',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Gray/image_5.jpeg',
    'description': ''
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Seafoam',
    'hex': '#4EC1D5',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Seafoam/image_1.jpeg',
    'description': 'seafoam'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Seafoam',
    'hex': '#4EC1D5',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Seafoam/image_2.jpeg',
    'description': 'Back view (Seafoam)'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Seafoam',
    'hex': '#4EC1D5',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Seafoam/image_3.jpeg',
    'description': ''
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Seafoam',
    'hex': '#4EC1D5',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Seafoam/image_4.jpeg',
    'description': ''
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Slate Blue',
    'hex': '#70CCFB',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Slate+Blue/image_1.jpeg',
    'description': 'slate blue'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Slate Blue',
    'hex': '#70CCFB',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Slate+Blue/image_2.jpeg',
    'description': 'Back view (Slate blue)'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Slate Blue',
    'hex': '#70CCFB',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Slate+Blue/image_3.jpeg',
    'description': 'Bottle cap (Slate blue)'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Slate Blue',
    'hex': '#70CCFB',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Slate+Blue/image_4.jpeg',
    'description': ''
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Slate Blue',
    'hex': '#70CCFB',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Slate+Blue/image_5.jpeg',
    'description': ''
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Trout Green',
    'hex': '#2CC0C4',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Trout+Green/image_1.jpeg',
    'description': 'trout green'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Trout Green',
    'hex': '#2CC0C4',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Trout+Green/image_2.jpeg',
    'description': 'Back view (Trout green)'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Trout Green',
    'hex': '#2CC0C4',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Trout+Green/image_3.jpeg',
    'description': 'Bottle cap (Trout green)'
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Trout Green',
    'hex': '#2CC0C4',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Trout+Green/image_4.jpeg',
    'description': ''
  },
  {
    'id': 10,
    'name': 'Nalgene Wide-Mouth Water Bottle - 32 fl. oz.',
    'category': 'accessories',
    'rating': 4.75,
    'color': 'Trout Green',
    'hex': '#2CC0C4',
    'price': 11.95,
    'url': 'https://rei-product.s3-us-west-1.amazonaws.com/10/Trout+Green/image_5.jpeg',
    'description': ''
  }
];